#!/bin/bash
#
# Make sure elasticsearch runs with a known JVM
#

fixJavaVersion() {
    [[ -e /etc/default/elasticsearch ]] \
        && perl -i -p -e 's!^(ES_)?JAVA_HOME=(.*)!ES_JAVA_HOME=/usr/lib/jvm/java-21-openjdk!' /etc/default/elasticsearch
}

post_install() {
    fixJavaVersion
}

post_upgrade() {
    fixJavaVersion
}
